version: "3.8"
services:
  # backend:
  #   build:
  #     dockerfile: ./deploy/server/Dockerfile
  #   # command: uvicorn main:app --reload --host 0.0.0.0
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - redis
  #     - postgres
  #   links:
  #     - redis
  #     - postgres

  redis:
    image: redis:6.2-alpine

  postgres:
    build:
      dockerfile: ./deploy/database/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: adaptive_storyfinder
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
